pkg/operator/status/condition: Handle Unknown in internalUnionCondition
The previous logic was built around a boolean assumption.  Running the
old logic against my new unit tests from this commit gave:

  $ go test ./pkg/operator/status/
  --- FAIL: TestDegraded (0.00s)
      --- FAIL: TestDegraded/two_present/one_available/one_unknown (0.00s)
      status_controller_test.go:293:   &v1.ClusterOperatorStatusCondition{
        Type:               "Available",
      - Status:             "Unknown",
      + Status:             "True",
        LastTransitionTime: v1.Time{},
      - Reason:             "TypeBAvailable",
      + Reason:             "AsExpected",
      - Message:            "TypeBAvailable: b is confused",
      + Message:            "TypeAAvailable: a is great\nTypeBAvailable: b is confused",
        }

      --- FAIL: TestDegraded/two_present/one_unavailable/one_unknown (0.00s)
      status_controller_test.go:293:   &v1.ClusterOperatorStatusCondition{
        Type:               "Available",
        Status:             "False",
        LastTransitionTime: v1.Time{},
      - Reason:             "MultipleConditionsMatching",
      + Reason:             "TypeAAvailable",
      - Message:            "TypeAAvailable: a is bad\nTypeBAvailable: b is confused",
      + Message:            "TypeAAvailable: a is bad",
        }

  FAIL
  FAIL  github.com/openshift/library-go/pkg/operator/status  0.013s

That was:

* Falsely claiming available in the first case, despite the presence
  of the unknown B.
* Not including the unknown B in the collated message, despite it also
  being not-good and therefore something that we should highlight for
  consumers.